### ISSUE TITLE
Getting NullPointerException 

### ISSUE THREAD

**Issue by y2kshane** [vikramkakkar/SublimePicker#16]
I'm getting a NullPointerException.

Process: com.dothis.dragonflymobile.dothis, PID: 11708
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dothis.dragonflymobile.dothis/com.dothis.dragonflymobile.dothis.create_todo.CreateToDoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.appeaser.sublimepickerlibrary.SublimePicker.initializePicker(com.appeaser.sublimepickerlibrary.helpers.SublimeOptions, com.appeaser.sublimepickerlibrary.helpers.SublimeListenerAdapter)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2430)
            at android.app.ActivityThread.access$900(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5305)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.appeaser.sublimepickerlibrary.SublimePicker.initializePicker(com.appeaser.sublimepickerlibrary.helpers.SublimeOptions, com.appeaser.sublimepickerlibrary.helpers.SublimeListenerAdapter)' on a null object reference
            at com.dothis.dragonflymobile.dothis.create_todo.CreateToDoActivity.onCreate(CreateToDoActivity.java:56)
            at android.app.Activity.performCreate(Activity.java:6865)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2430)
            at android.app.ActivityThread.access$900(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5305)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

This is my code
```
      mListener = new SublimeListenerAdapter() {
            @Override
            public void onCancelled() {
                // Handle click on `Cancel` button
            }

            @Override
            public void onDateTimeRecurrenceSet(SublimePicker sublimePicker,
                                                int year, int monthOfYear, int dayOfMonth,
                                                int hourOfDay, int minute,
                                                SublimeRecurrencePicker.RecurrenceOption recurrenceOption,
                                                String recurrenceRule) {
                // Handle click on `OK` button
            }
        };


        SublimeOptions options=new SublimeOptions();
        options.setDisplayOptions(SublimeOptions.ACTIVATE_TIME_PICKER
                | SublimeOptions.ACTIVATE_RECURRENCE_PICKER);

        SublimePicker mSublimePicker;
        mSublimePicker = (SublimePicker) findViewById(R.id.sublime_picker);
// Passing `null` to apply default options
        mSublimePicker.initializePicker(options, mListener);

```

**Comment by vikramkakkar** [comment]
From the looks of it, `mSublimePicker` is being initialized to `null` here:

     mSublimePicker = (SublimePicker) findViewById(R.id.sublime_picker);

Please make sure that `setContentView(...)` has been called with a layout resource containing a `SublimePicker` with id `sublime_picker`. If you are inflating a layout explicitly, use `inflatedView.findViewById(R.id.sublime_picker)` instead. 

If this doesn't help, post your entire `onCreate(Bundle)` method here and I may be able to spot something.
