### ISSUE TITLE
android.view.InflateException: Binary XML file line #2: Error inflating class com.appeaser.sublimepickerlibrary.SublimePicker

### ISSUE THREAD

**Issue by leguang** [vikramkakkar/SublimePicker#35]
Hello, your demo can be normal operation, but when I copied to my project, it is wrong.
android.view.InflateException: Binary XML file line #2: Error inflating class com.appeaser.sublimepickerlibrary.SublimePicker

Is there any other places I have not noticed?

My Gradle dependency
compile 'com.appeaser.sublimepickerlibrary:sublimepickerlibrary:2.1.1'

**Comment by vikramkakkar** [comment]
Hi, can you please check issue #25? The problem could be occurring on the android framework side. If not, please provide the complete stacktrace. Instruction are listed in the issue thread.

**Comment by Mohit-Soni** [comment]
Hi, I am facing the same issue. I am trying to add SublimeDatePicker in layout as an individual widget.

Here is the stack trace:

`06-30 11:42:35.111 29482-29482/com.wirecard E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.wirecard, PID: 29482
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wirecard/com.wirecard.activities.transactions.DateFilterActivity}: android.view.InflateException: Binary XML file line #32: Binary XML file line #13: Error inflating class com.appeaser.sublimepickerlibrary.datepicker.SublimeDatePicker
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                               Caused by: android.view.InflateException: Binary XML file line #32: Binary XML file line #13: Error inflating class com.appeaser.sublimepickerlibrary.datepicker.SublimeDatePicker
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                  at com.wirecard.activities.transactions.DateFilterActivity.onCreate(DateFilterActivity.java:19)
                                                                  at android.app.Activity.performCreate(Activity.java:6245)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                               Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.appeaser.sublimepickerlibrary.datepicker.SublimeDatePicker
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                  at com.wirecard.activities.transactions.DateFilterActivity.onCreate(DateFilterActivity.java:19) 
                                                                  at android.app.Activity.performCreate(Activity.java:6245) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                  at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                  at com.wirecard.activities.transactions.DateFilterActivity.onCreate(DateFilterActivity.java:19) 
                                                                  at android.app.Activity.performCreate(Activity.java:6245) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                               Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                  at android.view.ViewGroup.addView(ViewGroup.java:4080)
                                                                  at android.view.ViewGroup.addView(ViewGroup.java:4062)
                                                                  at com.appeaser.sublimepickerlibrary.datepicker.SublimeDatePicker.initializeLayout(SublimeDatePicker.java:169)
                                                                  at com.appeaser.sublimepickerlibrary.datepicker.SublimeDatePicker.<init>(SublimeDatePicker.java:130)
                                                                  at com.appeaser.sublimepickerlibrary.datepicker.SublimeDatePicker.<init>(SublimeDatePicker.java:125)
                                                                  at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                  at com.wirecard.activities.transactions.DateFilterActivity.onCreate(DateFilterActivity.java:19) 
                                                                  at android.app.Activity.performCreate(Activity.java:6245) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) `

Could you please help me?

**Comment by vikramkakkar** [comment]
@Mohit-Soni To add `SublimeDatePicker` independently, override the following attrs under your app's base theme:

    <style name="AppTheme" parent="BaseAppTheme">
        ....
        ....
        <item name="spHeaderBackgroundPtr">?attr/colorAccent</item>
        <item name="spPrimaryTextSecondaryWhenActivatedMaterialInversePtr">@color/sp_multi_use_text_light   </item>
        <item name="spNumbersTextColorPtr">@color/sp_text_color_primary_activated_light</item>
        <item name="spNumbersInnerTextColorPtr">@color/sp_text_color_secondary_activated_light</item>
        <item name="spNumbersBackgroundColorPtr">#ffdddddd</item>
        
        <item name="spLandscapeOkActionDrawable">@drawable/checkmark_medium_ff</item>
        <item name="spLandscapeCancelActionDrawable">@drawable/cancel_medium_ff</item>
    </style>

Now, this should work fine:

    <com.appeaser.sublimepickerlibrary.datepicker.SublimeDatePicker
        android:id="@+id/date_picker"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>

**Comment by Mohit-Soni** [comment]
@vikramkakkar - Still not working below is the stack trace:

`
06-30 18:42:17.445 13088-13088/com.wirecard E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.wirecard, PID: 13088
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
                                                                  at com.appeaser.sublimepickerlibrary.datepicker.DayPickerView.onLayout(DayPickerView.java:280)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
                                                                  at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
                                                                  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                  at android.view.View.layout(View.java:16646)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1943)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:746)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                              	at java.lang.reflect.Method.invo`

**Comment by lukaspili** [comment]
@vikramkakkar i'm having the same error

**Comment by julesanchez** [comment]
It misses `spCalendarDayTextColorPtr`,` spLandscapeButtonModeOkCancelButtonStyle` and `spLandscapeButtonModeSwitcherButtonStyle` attributes. Try these :

    <item name="spHeaderBackgroundPtr">?attr/colorAccent</item>
    <item name="spCalendarDayTextColorPtr">@color/sp_primary_text_dark</item>
    <item name="spPrimaryTextSecondaryWhenActivatedMaterialInversePtr">@color/sp_multi_use_text_light   </item>
    <item name="spNumbersTextColorPtr">@color/sp_text_color_primary_activated_light</item>
    <item name="spNumbersInnerTextColorPtr">@color/sp_text_color_secondary_activated_light</item>
    <item name="spNumbersBackgroundColorPtr">#ffdddddd</item>
    
    <item name="spLandscapeOkActionDrawable">@drawable/checkmark_medium_ff</item>
    <item name="spLandscapeCancelActionDrawable">@drawable/cancel_medium_ff</item>
    <item name="spLandscapeButtonModeOkCancelButtonStyle">@style/SButtonBarButtonStyle</item>
    <item name="spLandscapeButtonModeSwitcherButtonStyle">@style/SInvertedButtonBarButtonStyle</item>

**Comment by narendrakothamire** [comment]
I am getting same error i want to use only SublimeDatePicker
