### ISSUE TITLE
NullPointerException : findViewById(int) on a null object reference

### ISSUE THREAD

**Issue by vidhipatel94** [vikramkakkar/SublimePicker#67]
`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
       at com.appeaser.sublimepickerlibrary.datepicker.DayPickerView.onLayout(DayPickerView.java:280)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:15686)
       at android.view.ViewGroup.layout(ViewGroup.java:5114)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5895)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5358)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
`

**Comment by ankitbatra11** [comment]
Did you manage to get it fixed? I am also facing the same issue but only in release version of my app with proguard enabled.

**Comment by deinlandel** [comment]
Try to add the following to your proguard rules:
```
#sublime picker
-keepnames class com.appeaser.sublimepickerlibrary.datepicker.** {
    <fields>;
    <methods>;
}
```
