### ISSUE TITLE
issue when using kotlin

### ISSUE THREAD

**Issue by Hpark11** [vikramkakkar/SublimePicker#83]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter recurrenceRule
        at blackburn.io.audigo_android.DateTimePickerFragment$listenerAdapter$1.onDateTimeRecurrenceSet(DateTimePickerFragment.kt)
        at com.appeaser.sublimepickerlibrary.SublimePicker$2.onOkay(SublimePicker.java:159)
        at com.appeaser.sublimepickerlibrary.common.ButtonLayout.onClick(ButtonLayout.java:222)
        at android.view.View.performClick(View.java:6205)
        at android.widget.TextView.performClick(TextView.java:11103)
        at android.view.View$PerformClick.run(View.java:23653)
        at android.os.Handler.handleCallback(Handler.java:751)

when onDateTimeRecurrenceSet is called, errors like above happen, cuz one of the override PickerCallback funtions (onDateTimeRecurrenceSet) has recurrenceRule which cannot be set as Optional even if recurrenceRule is not nullable..

**Comment by erickogi** [comment]
How did you solve it
