### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference

### ISSUE THREAD

**Issue by daniebruwer** [vikramkakkar/SublimePicker#85]
implementation 'com.appeaser.sublimepickerlibrary:sublimepickerlibrary:2.1.1'

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference
       at com.appeaser.sublimepickerlibrary.SublimePicker$SavedState.writeToParcel(SublimePicker.java:499)
       at android.os.Parcel.writeParcelable(Parcel.java:1792)
       at android.os.Parcel.writeValue(Parcel.java:1698)
       at android.os.Parcel.writeSparseArray(Parcel.java:966)
       at android.os.Parcel.writeValue(Parcel.java:1723)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:838)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1546)
       at android.os.Bundle.writeToParcel(Bundle.java:1232)
       at android.os.Parcel.writeBundle(Parcel.java:878)
       at android.os.Parcel.writeValue(Parcel.java:1689)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:838)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1546)
       at android.os.Bundle.writeToParcel(Bundle.java:1232)
       at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4634)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4552)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by vikramkakkar** [comment]
@daniebruwer I'm not able to reproduce this. Can you please provide some more info on this? Is this happening on a specific version, picker combination/options?

**Comment by daniebruwer** [comment]
@vikramkakkar it seems to be only on HUAWEI1 00% Operating Systems> 100% 8
8.1.0 
All the details I have on Fabric link below
http://crashes.to/s/efecbd65a26

**Comment by ofir-bar5** [comment]
It happened to me.
Apparently, somewhere in your code, you are passing a null value to an enum that is not nullable.
So for example, if you have this object:

data class ExampleObject(
dayOfTheWeek : Day ,// Enum is not nullable
id : Int
)

Change it to 
data class ExampleObject(
dayOfTheWeek : Day? // Enum is nullable
id : Int
)
